---
name: "Terraform Version Detector"
description: "Detects required_version of Terraform for the specified directory."
author: "skokado"

inputs:
  path:
    type: string
    description: "Relative directory path to Terraform working directory."
    default: "."

outputs:
  terraform-version:
    description: "The detected Terraform version."
    value: ${{ steps.detect-version.outputs.terraform }}

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a # v7.1.5
      with:
        enable-cache: false

    - name : Install dependencies
      shell: bash
      env:
        UV_WORKING_DIRECTORY: ${{ github.action_path }}
      run: uv sync

    - name: main
      id: detect-version
      shell: bash
      env:
        UV_WORKING_DIRECTORY: ${{ github.action_path }}
      run: |
        uv run main.py --path ${{ github.workspace }}/${{ inputs.path }} > result
        echo "terraform=$(cat result)" >> $GITHUB_OUTPUT
